### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by vutondesign** [herohamp/status#1]
If `hampton.pw` was down, usually all the subdomains would also be down, meaning `status.hampton.pw` wouldn't work either?

**Comment by herohamp** [comment]
Nope, status is hosted on github pages, while the rest are distributed throughout my 4 servers (Mail server, vps, and 2 home servers)
Due to me not hosting them all at one place, individual stuff can go down

**Comment by vutondesign** [comment]
Ah, that makes more sense 👍
